version: "3"
services:
  mongo:
    container_name: dicty-mongo-container
    image: mongo:5.0
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  api:
    container_name: dicty-container
    image: node:16
    working_dir: /usr/src/dicty
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug2"
    volumes:
      - ./dist:/usr/src/dicty/dist
      - ./package.json:/usr/src/dicty/package.json
    ports:
      - "5000:5000"
      - "9222:9222"
    links:
      - mongo